variables:
  # buster is based on the v2.x branch and not master
  SKIP_RELEASE_PATTERN: /buster/

stages:
  - build

include:
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "/package-build-raspios-snapshot.yml"
  - local: debian/gitlab-ci.yml
    rules:
      - if: $CI_COMMIT_BRANCH =~ /^raspios\/.*/
      - exists:
          - debian/gitlab-ci.yml

