# SPDX-License-Identifier: GPL-2.0-or-later
#
# SPDX-FileCopyrightText: 2024 KUNBUS GmbH

variables:
  # buster is based on the v2.x branch and not master
  # bullseye is based on the 3.x branch
  SKIP_RELEASE_PATTERN: /buster|bullseye/

# Build a snapshot debian package from current master
include:
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "base.yml"
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "/package-snapshot-debian.yml"
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "/reuse-lint.yml"
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "/check-commit/lint-commit.yml"
  - local: debian/gitlab-ci.yml
    rules:
      - if: $CI_COMMIT_BRANCH =~ /^(raspios|debian)\/.*/
        exists:
          - debian/gitlab-ci.yml

# build the repo
test-build-cmake:
  image: registry.gitlab.com/revolutionpi/infrastructure/docker-images/build-container/build-container-bullseye:arm64-latest
  tags:
    - docker
    - host-arm64
  stage: build
  script:
    - apt update
    - apt install -y cmake pkg-config systemd libftdi1-dev xxd scdoc
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH

test:
  image: registry.gitlab.com/revolutionpi/infrastructure/docker-images/build-container/build-container-bullseye:arm64-latest
  tags:
    - docker
    - host-arm64
    - self-hosted
  stage: test
  script:
    - apt update && apt install -y kyua atf-sh
    - kyua test
    - kyua report-junit --output report.xml
  artifacts:
    reports:
      junit: ${CI_PROJECT_DIR}/report.xml
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
